import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import {AppProvider} from "@/components/AppContext";
import { Toaster } from "react-hot-toast"

const roboto = Roboto({ subsets: ["latin"], weight: ['400','500','700'] });

export const metadata = {
  title: "NgOo Coffee",
  description: "Generated by NgOo Coffee",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="icon" href="/coffee-shop.png"/>
      </head>
      <body className={roboto.className}>
        <main className="mx-auto">
          <AppProvider>
              <Toaster containerStyle={{
                marginTop: '80px',
                right: '-80%',
              }}/>
              <Header />
              {children}
              <Footer/>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
